latest deploy

diff --git a/.github/workflows/az-botdefense-xc-bigip-apply.yml b/.github/workflows/az-botdefense-xc-bigip-apply.yml
--- a/.github/workflows/az-botdefense-xc-bigip-apply.yml
+++ b/.github/workflows/az-botdefense-xc-bigip-apply.yml
@@ -154,7 +154,7 @@ jobs:
       - name: Terraform Apply
         if: github.ref == 'refs/heads/az-botdefense-apply' && github.event_name == 'push'
         run: |
-          rm -rf manifest.yaml
+          rm -f manifest.yaml
           mv az-xcbotdefense-app.yaml manifest.yaml
           cat manifest.yaml
           terraform apply -auto-approve -input=false
@@ -232,3 +232,78 @@ jobs:
         - name: Terraform Apply
           if: github.ref == 'refs/heads/az-botdefense-apply' && github.event_name == 'push'
           run: terraform apply -auto-approve -input=false
+
+
+#  terraform_bot:
+#    name: "Configure Bot Defense on BIGIP"
+#    runs-on: ubuntu-latest
+#    #needs: [terraform_bigip]
+#    defaults:
+#      run:
+#        working-directory: ./azure/bigip/bot-defense
+#    steps:
+#      - name: Checkout
+#        uses: actions/checkout@v3
+#
+#      - name: Setup Terraform
+#        uses: hashicorp/setup-terraform@v2
+#        with:
+#          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
+#
+#      - name: Setup Terraform Backend
+#        id: backend
+#        run: |
+#          cat > backend.tf << EOF
+#          terraform {
+#            cloud {
+#              organization = "${{ secrets.TF_CLOUD_ORGANIZATION }}"
+#              workspaces {
+#                name = "${{ secrets.TF_CLOUD_WORKSPACE_BOTDEFENSE }}"
+#              }
+#            }
+#          }
+#          EOF
+#      - name: Terraform Init
+#        id: init
+#        run: terraform init
+#
+#      - name: Terraform Validate
+#        id: validate
+#        run: terraform validate -no-color
+#
+#      - name: Terraform Plan
+#        id: plan
+#        if: github.event_name == 'pull_request'
+#        run: terraform plan -no-color -input=false
+#        continue-on-error: true
+#
+#      - uses: actions/github-script@v6
+#        if: github.event_name == 'pull_request'
+#        env:
+#          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
+#        with:
+#          github-token: ${{ secrets.GITHUB_TOKEN }}
+#          script: |
+#            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
+#            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+#            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
+#            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+#            <details><summary>Show Plan</summary>
+#            \`\`\`\n
+#            ${process.env.PLAN}
+#            \`\`\`
+#            </details>
+#            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+#            github.rest.issues.createComment({
+#              issue_number: context.issue.number,
+#              owner: context.repo.owner,
+#              repo: context.repo.repo,
+#              body: output
+#            })
+#      - name: Terraform Plan Status
+#        if: steps.plan.outcome == 'failure'
+#        run: exit 1
+#
+#      - name: Terraform Apply
+#        if: github.ref == 'refs/heads/deploy-bot-defense-gcp' && github.event_name == 'push'
+#        run: terraform apply -auto-approve -input=false
